// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jarvis/mapping/dbow/proto/vocabulary_data.proto

#include "jarvis/mapping/dbow/proto/vocabulary_data.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace jarvis {
namespace mapping {
namespace dbow {
namespace proto {
PROTOBUF_CONSTEXPR VocabularyOption::VocabularyOption(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.score_type_)*/0u
  , /*decltype(_impl_.weighting_type_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct VocabularyOptionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VocabularyOptionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VocabularyOptionDefaultTypeInternal() {}
  union {
    VocabularyOption _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VocabularyOptionDefaultTypeInternal _VocabularyOption_default_instance_;
PROTOBUF_CONSTEXPR Descriptor::Descriptor(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.brif_bitset_)*/{}
  , /*decltype(_impl_._brif_bitset_cached_byte_size_)*/{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DescriptorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DescriptorDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DescriptorDefaultTypeInternal() {}
  union {
    Descriptor _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DescriptorDefaultTypeInternal _Descriptor_default_instance_;
PROTOBUF_CONSTEXPR VocabularyData_Node::VocabularyData_Node(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.childrens_ids_)*/{}
  , /*decltype(_impl_._childrens_ids_cached_byte_size_)*/{0}
  , /*decltype(_impl_.id_)*/uint64_t{0u}
  , /*decltype(_impl_.parent_id_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct VocabularyData_NodeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VocabularyData_NodeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VocabularyData_NodeDefaultTypeInternal() {}
  union {
    VocabularyData_Node _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VocabularyData_NodeDefaultTypeInternal _VocabularyData_Node_default_instance_;
PROTOBUF_CONSTEXPR VocabularyData_NodeData::VocabularyData_NodeData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.descriptors_)*/nullptr
  , /*decltype(_impl_.weight_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct VocabularyData_NodeDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VocabularyData_NodeDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VocabularyData_NodeDataDefaultTypeInternal() {}
  union {
    VocabularyData_NodeData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VocabularyData_NodeDataDefaultTypeInternal _VocabularyData_NodeData_default_instance_;
PROTOBUF_CONSTEXPR VocabularyData_Info::VocabularyData_Info(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.descriptor_type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.option_)*/nullptr
  , /*decltype(_impl_.descriptor_rotated_)*/0
  , /*decltype(_impl_.branching_factor_)*/0
  , /*decltype(_impl_.depth_levels_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct VocabularyData_InfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VocabularyData_InfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VocabularyData_InfoDefaultTypeInternal() {}
  union {
    VocabularyData_Info _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VocabularyData_InfoDefaultTypeInternal _VocabularyData_Info_default_instance_;
PROTOBUF_CONSTEXPR VocabularyData_NodeDatasEntry_DoNotUse::VocabularyData_NodeDatasEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct VocabularyData_NodeDatasEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VocabularyData_NodeDatasEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VocabularyData_NodeDatasEntry_DoNotUseDefaultTypeInternal() {}
  union {
    VocabularyData_NodeDatasEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VocabularyData_NodeDatasEntry_DoNotUseDefaultTypeInternal _VocabularyData_NodeDatasEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR VocabularyData_NodesEntry_DoNotUse::VocabularyData_NodesEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct VocabularyData_NodesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VocabularyData_NodesEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VocabularyData_NodesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    VocabularyData_NodesEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VocabularyData_NodesEntry_DoNotUseDefaultTypeInternal _VocabularyData_NodesEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR VocabularyData::VocabularyData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.node_datas_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.nodes_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.word_ids_)*/{}
  , /*decltype(_impl_._word_ids_cached_byte_size_)*/{0}
  , /*decltype(_impl_.info_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct VocabularyDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VocabularyDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VocabularyDataDefaultTypeInternal() {}
  union {
    VocabularyData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VocabularyDataDefaultTypeInternal _VocabularyData_default_instance_;
PROTOBUF_CONSTEXPR VocabularyDatas::VocabularyDatas(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.vocabulary_datas_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct VocabularyDatasDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VocabularyDatasDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VocabularyDatasDefaultTypeInternal() {}
  union {
    VocabularyDatas _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VocabularyDatasDefaultTypeInternal _VocabularyDatas_default_instance_;
}  // namespace proto
}  // namespace dbow
}  // namespace mapping
}  // namespace jarvis
static ::_pb::Metadata file_level_metadata_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto[9];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto = nullptr;

const uint32_t TableStruct_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyOption, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyOption, _impl_.score_type_),
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyOption, _impl_.weighting_type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::Descriptor, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::Descriptor, _impl_.brif_bitset_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_Node, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_Node, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_Node, _impl_.parent_id_),
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_Node, _impl_.childrens_ids_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_NodeData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_NodeData, _impl_.weight_),
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_NodeData, _impl_.descriptors_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_Info, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_Info, _impl_.descriptor_type_),
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_Info, _impl_.descriptor_rotated_),
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_Info, _impl_.branching_factor_),
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_Info, _impl_.depth_levels_),
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_Info, _impl_.option_),
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_NodeDatasEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_NodeDatasEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_NodeDatasEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_NodeDatasEntry_DoNotUse, value_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_NodesEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_NodesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_NodesEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData_NodesEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData, _impl_.info_),
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData, _impl_.node_datas_),
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData, _impl_.nodes_),
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyData, _impl_.word_ids_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyDatas, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::jarvis::mapping::dbow::proto::VocabularyDatas, _impl_.vocabulary_datas_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::jarvis::mapping::dbow::proto::VocabularyOption)},
  { 8, -1, -1, sizeof(::jarvis::mapping::dbow::proto::Descriptor)},
  { 15, -1, -1, sizeof(::jarvis::mapping::dbow::proto::VocabularyData_Node)},
  { 24, -1, -1, sizeof(::jarvis::mapping::dbow::proto::VocabularyData_NodeData)},
  { 32, -1, -1, sizeof(::jarvis::mapping::dbow::proto::VocabularyData_Info)},
  { 43, 51, -1, sizeof(::jarvis::mapping::dbow::proto::VocabularyData_NodeDatasEntry_DoNotUse)},
  { 53, 61, -1, sizeof(::jarvis::mapping::dbow::proto::VocabularyData_NodesEntry_DoNotUse)},
  { 63, -1, -1, sizeof(::jarvis::mapping::dbow::proto::VocabularyData)},
  { 73, -1, -1, sizeof(::jarvis::mapping::dbow::proto::VocabularyDatas)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::jarvis::mapping::dbow::proto::_VocabularyOption_default_instance_._instance,
  &::jarvis::mapping::dbow::proto::_Descriptor_default_instance_._instance,
  &::jarvis::mapping::dbow::proto::_VocabularyData_Node_default_instance_._instance,
  &::jarvis::mapping::dbow::proto::_VocabularyData_NodeData_default_instance_._instance,
  &::jarvis::mapping::dbow::proto::_VocabularyData_Info_default_instance_._instance,
  &::jarvis::mapping::dbow::proto::_VocabularyData_NodeDatasEntry_DoNotUse_default_instance_._instance,
  &::jarvis::mapping::dbow::proto::_VocabularyData_NodesEntry_DoNotUse_default_instance_._instance,
  &::jarvis::mapping::dbow::proto::_VocabularyData_default_instance_._instance,
  &::jarvis::mapping::dbow::proto::_VocabularyDatas_default_instance_._instance,
};

const char descriptor_table_protodef_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n/jarvis/mapping/dbow/proto/vocabulary_d"
  "ata.proto\022\031jarvis.mapping.dbow.proto\">\n\020"
  "VocabularyOption\022\022\n\nscore_type\030\001 \001(\r\022\026\n\016"
  "weighting_type\030\002 \001(\r\"!\n\nDescriptor\022\023\n\013br"
  "if_bitset\030\001 \003(\r\"\370\005\n\016VocabularyData\022<\n\004in"
  "fo\030\001 \001(\0132..jarvis.mapping.dbow.proto.Voc"
  "abularyData.Info\022L\n\nnode_datas\030\002 \003(\01328.j"
  "arvis.mapping.dbow.proto.VocabularyData."
  "NodeDatasEntry\022C\n\005nodes\030\003 \003(\01324.jarvis.m"
  "apping.dbow.proto.VocabularyData.NodesEn"
  "try\022\020\n\010word_ids\030\004 \003(\004\032<\n\004Node\022\n\n\002id\030\001 \001("
  "\004\022\021\n\tparent_id\030\002 \001(\004\022\025\n\rchildrens_ids\030\004 "
  "\003(\004\032V\n\010NodeData\022\016\n\006weight\030\001 \001(\001\022:\n\013descr"
  "iptors\030\002 \001(\0132%.jarvis.mapping.dbow.proto"
  ".Descriptor\032\250\001\n\004Info\022\027\n\017descriptor_type\030"
  "\001 \001(\t\022\032\n\022descriptor_rotated\030\002 \001(\005\022\030\n\020bra"
  "nching_factor\030\003 \001(\005\022\024\n\014depth_levels\030\004 \001("
  "\005\022;\n\006option\030\005 \001(\0132+.jarvis.mapping.dbow."
  "proto.VocabularyOption\032d\n\016NodeDatasEntry"
  "\022\013\n\003key\030\001 \001(\004\022A\n\005value\030\002 \001(\01322.jarvis.ma"
  "pping.dbow.proto.VocabularyData.NodeData"
  ":\0028\001\032\\\n\nNodesEntry\022\013\n\003key\030\001 \001(\004\022=\n\005value"
  "\030\002 \001(\0132..jarvis.mapping.dbow.proto.Vocab"
  "ularyData.Node:\0028\001\"V\n\017VocabularyDatas\022C\n"
  "\020vocabulary_datas\030\001 \003(\0132).jarvis.mapping"
  ".dbow.proto.VocabularyDatab\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto = {
    false, false, 1034, descriptor_table_protodef_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto,
    "jarvis/mapping/dbow/proto/vocabulary_data.proto",
    &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_once, nullptr, 0, 9,
    schemas, file_default_instances, TableStruct_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto::offsets,
    file_level_metadata_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto, file_level_enum_descriptors_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto,
    file_level_service_descriptors_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_getter() {
  return &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto(&descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto);
namespace jarvis {
namespace mapping {
namespace dbow {
namespace proto {

// ===================================================================

class VocabularyOption::_Internal {
 public:
};

VocabularyOption::VocabularyOption(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:jarvis.mapping.dbow.proto.VocabularyOption)
}
VocabularyOption::VocabularyOption(const VocabularyOption& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  VocabularyOption* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.score_type_){}
    , decltype(_impl_.weighting_type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.score_type_, &from._impl_.score_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.weighting_type_) -
    reinterpret_cast<char*>(&_impl_.score_type_)) + sizeof(_impl_.weighting_type_));
  // @@protoc_insertion_point(copy_constructor:jarvis.mapping.dbow.proto.VocabularyOption)
}

inline void VocabularyOption::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.score_type_){0u}
    , decltype(_impl_.weighting_type_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

VocabularyOption::~VocabularyOption() {
  // @@protoc_insertion_point(destructor:jarvis.mapping.dbow.proto.VocabularyOption)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void VocabularyOption::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void VocabularyOption::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void VocabularyOption::Clear() {
// @@protoc_insertion_point(message_clear_start:jarvis.mapping.dbow.proto.VocabularyOption)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.score_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.weighting_type_) -
      reinterpret_cast<char*>(&_impl_.score_type_)) + sizeof(_impl_.weighting_type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VocabularyOption::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 score_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.score_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 weighting_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.weighting_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* VocabularyOption::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:jarvis.mapping.dbow.proto.VocabularyOption)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 score_type = 1;
  if (this->_internal_score_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_score_type(), target);
  }

  // uint32 weighting_type = 2;
  if (this->_internal_weighting_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_weighting_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:jarvis.mapping.dbow.proto.VocabularyOption)
  return target;
}

size_t VocabularyOption::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:jarvis.mapping.dbow.proto.VocabularyOption)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 score_type = 1;
  if (this->_internal_score_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_score_type());
  }

  // uint32 weighting_type = 2;
  if (this->_internal_weighting_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_weighting_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData VocabularyOption::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    VocabularyOption::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*VocabularyOption::GetClassData() const { return &_class_data_; }


void VocabularyOption::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<VocabularyOption*>(&to_msg);
  auto& from = static_cast<const VocabularyOption&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:jarvis.mapping.dbow.proto.VocabularyOption)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_score_type() != 0) {
    _this->_internal_set_score_type(from._internal_score_type());
  }
  if (from._internal_weighting_type() != 0) {
    _this->_internal_set_weighting_type(from._internal_weighting_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void VocabularyOption::CopyFrom(const VocabularyOption& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jarvis.mapping.dbow.proto.VocabularyOption)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VocabularyOption::IsInitialized() const {
  return true;
}

void VocabularyOption::InternalSwap(VocabularyOption* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VocabularyOption, _impl_.weighting_type_)
      + sizeof(VocabularyOption::_impl_.weighting_type_)
      - PROTOBUF_FIELD_OFFSET(VocabularyOption, _impl_.score_type_)>(
          reinterpret_cast<char*>(&_impl_.score_type_),
          reinterpret_cast<char*>(&other->_impl_.score_type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata VocabularyOption::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_getter, &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_once,
      file_level_metadata_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto[0]);
}

// ===================================================================

class Descriptor::_Internal {
 public:
};

Descriptor::Descriptor(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:jarvis.mapping.dbow.proto.Descriptor)
}
Descriptor::Descriptor(const Descriptor& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Descriptor* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.brif_bitset_){from._impl_.brif_bitset_}
    , /*decltype(_impl_._brif_bitset_cached_byte_size_)*/{0}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:jarvis.mapping.dbow.proto.Descriptor)
}

inline void Descriptor::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.brif_bitset_){arena}
    , /*decltype(_impl_._brif_bitset_cached_byte_size_)*/{0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Descriptor::~Descriptor() {
  // @@protoc_insertion_point(destructor:jarvis.mapping.dbow.proto.Descriptor)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Descriptor::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.brif_bitset_.~RepeatedField();
}

void Descriptor::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Descriptor::Clear() {
// @@protoc_insertion_point(message_clear_start:jarvis.mapping.dbow.proto.Descriptor)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.brif_bitset_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Descriptor::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated uint32 brif_bitset = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_brif_bitset(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 8) {
          _internal_add_brif_bitset(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Descriptor::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:jarvis.mapping.dbow.proto.Descriptor)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated uint32 brif_bitset = 1;
  {
    int byte_size = _impl_._brif_bitset_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          1, _internal_brif_bitset(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:jarvis.mapping.dbow.proto.Descriptor)
  return target;
}

size_t Descriptor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:jarvis.mapping.dbow.proto.Descriptor)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint32 brif_bitset = 1;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt32Size(this->_impl_.brif_bitset_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._brif_bitset_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Descriptor::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Descriptor::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Descriptor::GetClassData() const { return &_class_data_; }


void Descriptor::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Descriptor*>(&to_msg);
  auto& from = static_cast<const Descriptor&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:jarvis.mapping.dbow.proto.Descriptor)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.brif_bitset_.MergeFrom(from._impl_.brif_bitset_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Descriptor::CopyFrom(const Descriptor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jarvis.mapping.dbow.proto.Descriptor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Descriptor::IsInitialized() const {
  return true;
}

void Descriptor::InternalSwap(Descriptor* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.brif_bitset_.InternalSwap(&other->_impl_.brif_bitset_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Descriptor::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_getter, &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_once,
      file_level_metadata_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto[1]);
}

// ===================================================================

class VocabularyData_Node::_Internal {
 public:
};

VocabularyData_Node::VocabularyData_Node(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:jarvis.mapping.dbow.proto.VocabularyData.Node)
}
VocabularyData_Node::VocabularyData_Node(const VocabularyData_Node& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  VocabularyData_Node* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.childrens_ids_){from._impl_.childrens_ids_}
    , /*decltype(_impl_._childrens_ids_cached_byte_size_)*/{0}
    , decltype(_impl_.id_){}
    , decltype(_impl_.parent_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.id_, &from._impl_.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.parent_id_) -
    reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.parent_id_));
  // @@protoc_insertion_point(copy_constructor:jarvis.mapping.dbow.proto.VocabularyData.Node)
}

inline void VocabularyData_Node::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.childrens_ids_){arena}
    , /*decltype(_impl_._childrens_ids_cached_byte_size_)*/{0}
    , decltype(_impl_.id_){uint64_t{0u}}
    , decltype(_impl_.parent_id_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

VocabularyData_Node::~VocabularyData_Node() {
  // @@protoc_insertion_point(destructor:jarvis.mapping.dbow.proto.VocabularyData.Node)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void VocabularyData_Node::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.childrens_ids_.~RepeatedField();
}

void VocabularyData_Node::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void VocabularyData_Node::Clear() {
// @@protoc_insertion_point(message_clear_start:jarvis.mapping.dbow.proto.VocabularyData.Node)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.childrens_ids_.Clear();
  ::memset(&_impl_.id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.parent_id_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.parent_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VocabularyData_Node::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 parent_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.parent_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated uint64 childrens_ids = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt64Parser(_internal_mutable_childrens_ids(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 32) {
          _internal_add_childrens_ids(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* VocabularyData_Node::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:jarvis.mapping.dbow.proto.VocabularyData.Node)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_id(), target);
  }

  // uint64 parent_id = 2;
  if (this->_internal_parent_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_parent_id(), target);
  }

  // repeated uint64 childrens_ids = 4;
  {
    int byte_size = _impl_._childrens_ids_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt64Packed(
          4, _internal_childrens_ids(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:jarvis.mapping.dbow.proto.VocabularyData.Node)
  return target;
}

size_t VocabularyData_Node::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:jarvis.mapping.dbow.proto.VocabularyData.Node)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint64 childrens_ids = 4;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt64Size(this->_impl_.childrens_ids_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._childrens_ids_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_id());
  }

  // uint64 parent_id = 2;
  if (this->_internal_parent_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_parent_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData VocabularyData_Node::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    VocabularyData_Node::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*VocabularyData_Node::GetClassData() const { return &_class_data_; }


void VocabularyData_Node::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<VocabularyData_Node*>(&to_msg);
  auto& from = static_cast<const VocabularyData_Node&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:jarvis.mapping.dbow.proto.VocabularyData.Node)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.childrens_ids_.MergeFrom(from._impl_.childrens_ids_);
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_parent_id() != 0) {
    _this->_internal_set_parent_id(from._internal_parent_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void VocabularyData_Node::CopyFrom(const VocabularyData_Node& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jarvis.mapping.dbow.proto.VocabularyData.Node)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VocabularyData_Node::IsInitialized() const {
  return true;
}

void VocabularyData_Node::InternalSwap(VocabularyData_Node* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.childrens_ids_.InternalSwap(&other->_impl_.childrens_ids_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VocabularyData_Node, _impl_.parent_id_)
      + sizeof(VocabularyData_Node::_impl_.parent_id_)
      - PROTOBUF_FIELD_OFFSET(VocabularyData_Node, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata VocabularyData_Node::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_getter, &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_once,
      file_level_metadata_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto[2]);
}

// ===================================================================

class VocabularyData_NodeData::_Internal {
 public:
  static const ::jarvis::mapping::dbow::proto::Descriptor& descriptors(const VocabularyData_NodeData* msg);
};

const ::jarvis::mapping::dbow::proto::Descriptor&
VocabularyData_NodeData::_Internal::descriptors(const VocabularyData_NodeData* msg) {
  return *msg->_impl_.descriptors_;
}
VocabularyData_NodeData::VocabularyData_NodeData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:jarvis.mapping.dbow.proto.VocabularyData.NodeData)
}
VocabularyData_NodeData::VocabularyData_NodeData(const VocabularyData_NodeData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  VocabularyData_NodeData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.descriptors_){nullptr}
    , decltype(_impl_.weight_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_descriptors()) {
    _this->_impl_.descriptors_ = new ::jarvis::mapping::dbow::proto::Descriptor(*from._impl_.descriptors_);
  }
  _this->_impl_.weight_ = from._impl_.weight_;
  // @@protoc_insertion_point(copy_constructor:jarvis.mapping.dbow.proto.VocabularyData.NodeData)
}

inline void VocabularyData_NodeData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.descriptors_){nullptr}
    , decltype(_impl_.weight_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

VocabularyData_NodeData::~VocabularyData_NodeData() {
  // @@protoc_insertion_point(destructor:jarvis.mapping.dbow.proto.VocabularyData.NodeData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void VocabularyData_NodeData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.descriptors_;
}

void VocabularyData_NodeData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void VocabularyData_NodeData::Clear() {
// @@protoc_insertion_point(message_clear_start:jarvis.mapping.dbow.proto.VocabularyData.NodeData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.descriptors_ != nullptr) {
    delete _impl_.descriptors_;
  }
  _impl_.descriptors_ = nullptr;
  _impl_.weight_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VocabularyData_NodeData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double weight = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.weight_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // .jarvis.mapping.dbow.proto.Descriptor descriptors = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_descriptors(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* VocabularyData_NodeData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:jarvis.mapping.dbow.proto.VocabularyData.NodeData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double weight = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_weight = this->_internal_weight();
  uint64_t raw_weight;
  memcpy(&raw_weight, &tmp_weight, sizeof(tmp_weight));
  if (raw_weight != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_weight(), target);
  }

  // .jarvis.mapping.dbow.proto.Descriptor descriptors = 2;
  if (this->_internal_has_descriptors()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::descriptors(this),
        _Internal::descriptors(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:jarvis.mapping.dbow.proto.VocabularyData.NodeData)
  return target;
}

size_t VocabularyData_NodeData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:jarvis.mapping.dbow.proto.VocabularyData.NodeData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .jarvis.mapping.dbow.proto.Descriptor descriptors = 2;
  if (this->_internal_has_descriptors()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.descriptors_);
  }

  // double weight = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_weight = this->_internal_weight();
  uint64_t raw_weight;
  memcpy(&raw_weight, &tmp_weight, sizeof(tmp_weight));
  if (raw_weight != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData VocabularyData_NodeData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    VocabularyData_NodeData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*VocabularyData_NodeData::GetClassData() const { return &_class_data_; }


void VocabularyData_NodeData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<VocabularyData_NodeData*>(&to_msg);
  auto& from = static_cast<const VocabularyData_NodeData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:jarvis.mapping.dbow.proto.VocabularyData.NodeData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_descriptors()) {
    _this->_internal_mutable_descriptors()->::jarvis::mapping::dbow::proto::Descriptor::MergeFrom(
        from._internal_descriptors());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_weight = from._internal_weight();
  uint64_t raw_weight;
  memcpy(&raw_weight, &tmp_weight, sizeof(tmp_weight));
  if (raw_weight != 0) {
    _this->_internal_set_weight(from._internal_weight());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void VocabularyData_NodeData::CopyFrom(const VocabularyData_NodeData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jarvis.mapping.dbow.proto.VocabularyData.NodeData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VocabularyData_NodeData::IsInitialized() const {
  return true;
}

void VocabularyData_NodeData::InternalSwap(VocabularyData_NodeData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VocabularyData_NodeData, _impl_.weight_)
      + sizeof(VocabularyData_NodeData::_impl_.weight_)
      - PROTOBUF_FIELD_OFFSET(VocabularyData_NodeData, _impl_.descriptors_)>(
          reinterpret_cast<char*>(&_impl_.descriptors_),
          reinterpret_cast<char*>(&other->_impl_.descriptors_));
}

::PROTOBUF_NAMESPACE_ID::Metadata VocabularyData_NodeData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_getter, &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_once,
      file_level_metadata_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto[3]);
}

// ===================================================================

class VocabularyData_Info::_Internal {
 public:
  static const ::jarvis::mapping::dbow::proto::VocabularyOption& option(const VocabularyData_Info* msg);
};

const ::jarvis::mapping::dbow::proto::VocabularyOption&
VocabularyData_Info::_Internal::option(const VocabularyData_Info* msg) {
  return *msg->_impl_.option_;
}
VocabularyData_Info::VocabularyData_Info(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:jarvis.mapping.dbow.proto.VocabularyData.Info)
}
VocabularyData_Info::VocabularyData_Info(const VocabularyData_Info& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  VocabularyData_Info* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.descriptor_type_){}
    , decltype(_impl_.option_){nullptr}
    , decltype(_impl_.descriptor_rotated_){}
    , decltype(_impl_.branching_factor_){}
    , decltype(_impl_.depth_levels_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.descriptor_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.descriptor_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_descriptor_type().empty()) {
    _this->_impl_.descriptor_type_.Set(from._internal_descriptor_type(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_option()) {
    _this->_impl_.option_ = new ::jarvis::mapping::dbow::proto::VocabularyOption(*from._impl_.option_);
  }
  ::memcpy(&_impl_.descriptor_rotated_, &from._impl_.descriptor_rotated_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.depth_levels_) -
    reinterpret_cast<char*>(&_impl_.descriptor_rotated_)) + sizeof(_impl_.depth_levels_));
  // @@protoc_insertion_point(copy_constructor:jarvis.mapping.dbow.proto.VocabularyData.Info)
}

inline void VocabularyData_Info::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.descriptor_type_){}
    , decltype(_impl_.option_){nullptr}
    , decltype(_impl_.descriptor_rotated_){0}
    , decltype(_impl_.branching_factor_){0}
    , decltype(_impl_.depth_levels_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.descriptor_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.descriptor_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

VocabularyData_Info::~VocabularyData_Info() {
  // @@protoc_insertion_point(destructor:jarvis.mapping.dbow.proto.VocabularyData.Info)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void VocabularyData_Info::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.descriptor_type_.Destroy();
  if (this != internal_default_instance()) delete _impl_.option_;
}

void VocabularyData_Info::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void VocabularyData_Info::Clear() {
// @@protoc_insertion_point(message_clear_start:jarvis.mapping.dbow.proto.VocabularyData.Info)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.descriptor_type_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.option_ != nullptr) {
    delete _impl_.option_;
  }
  _impl_.option_ = nullptr;
  ::memset(&_impl_.descriptor_rotated_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.depth_levels_) -
      reinterpret_cast<char*>(&_impl_.descriptor_rotated_)) + sizeof(_impl_.depth_levels_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VocabularyData_Info::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string descriptor_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_descriptor_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "jarvis.mapping.dbow.proto.VocabularyData.Info.descriptor_type"));
        } else
          goto handle_unusual;
        continue;
      // int32 descriptor_rotated = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.descriptor_rotated_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 branching_factor = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.branching_factor_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 depth_levels = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.depth_levels_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .jarvis.mapping.dbow.proto.VocabularyOption option = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_option(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* VocabularyData_Info::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:jarvis.mapping.dbow.proto.VocabularyData.Info)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string descriptor_type = 1;
  if (!this->_internal_descriptor_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_descriptor_type().data(), static_cast<int>(this->_internal_descriptor_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "jarvis.mapping.dbow.proto.VocabularyData.Info.descriptor_type");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_descriptor_type(), target);
  }

  // int32 descriptor_rotated = 2;
  if (this->_internal_descriptor_rotated() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_descriptor_rotated(), target);
  }

  // int32 branching_factor = 3;
  if (this->_internal_branching_factor() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_branching_factor(), target);
  }

  // int32 depth_levels = 4;
  if (this->_internal_depth_levels() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_depth_levels(), target);
  }

  // .jarvis.mapping.dbow.proto.VocabularyOption option = 5;
  if (this->_internal_has_option()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::option(this),
        _Internal::option(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:jarvis.mapping.dbow.proto.VocabularyData.Info)
  return target;
}

size_t VocabularyData_Info::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:jarvis.mapping.dbow.proto.VocabularyData.Info)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string descriptor_type = 1;
  if (!this->_internal_descriptor_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_descriptor_type());
  }

  // .jarvis.mapping.dbow.proto.VocabularyOption option = 5;
  if (this->_internal_has_option()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.option_);
  }

  // int32 descriptor_rotated = 2;
  if (this->_internal_descriptor_rotated() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_descriptor_rotated());
  }

  // int32 branching_factor = 3;
  if (this->_internal_branching_factor() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_branching_factor());
  }

  // int32 depth_levels = 4;
  if (this->_internal_depth_levels() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_depth_levels());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData VocabularyData_Info::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    VocabularyData_Info::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*VocabularyData_Info::GetClassData() const { return &_class_data_; }


void VocabularyData_Info::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<VocabularyData_Info*>(&to_msg);
  auto& from = static_cast<const VocabularyData_Info&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:jarvis.mapping.dbow.proto.VocabularyData.Info)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_descriptor_type().empty()) {
    _this->_internal_set_descriptor_type(from._internal_descriptor_type());
  }
  if (from._internal_has_option()) {
    _this->_internal_mutable_option()->::jarvis::mapping::dbow::proto::VocabularyOption::MergeFrom(
        from._internal_option());
  }
  if (from._internal_descriptor_rotated() != 0) {
    _this->_internal_set_descriptor_rotated(from._internal_descriptor_rotated());
  }
  if (from._internal_branching_factor() != 0) {
    _this->_internal_set_branching_factor(from._internal_branching_factor());
  }
  if (from._internal_depth_levels() != 0) {
    _this->_internal_set_depth_levels(from._internal_depth_levels());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void VocabularyData_Info::CopyFrom(const VocabularyData_Info& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jarvis.mapping.dbow.proto.VocabularyData.Info)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VocabularyData_Info::IsInitialized() const {
  return true;
}

void VocabularyData_Info::InternalSwap(VocabularyData_Info* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.descriptor_type_, lhs_arena,
      &other->_impl_.descriptor_type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VocabularyData_Info, _impl_.depth_levels_)
      + sizeof(VocabularyData_Info::_impl_.depth_levels_)
      - PROTOBUF_FIELD_OFFSET(VocabularyData_Info, _impl_.option_)>(
          reinterpret_cast<char*>(&_impl_.option_),
          reinterpret_cast<char*>(&other->_impl_.option_));
}

::PROTOBUF_NAMESPACE_ID::Metadata VocabularyData_Info::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_getter, &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_once,
      file_level_metadata_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto[4]);
}

// ===================================================================

VocabularyData_NodeDatasEntry_DoNotUse::VocabularyData_NodeDatasEntry_DoNotUse() {}
VocabularyData_NodeDatasEntry_DoNotUse::VocabularyData_NodeDatasEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void VocabularyData_NodeDatasEntry_DoNotUse::MergeFrom(const VocabularyData_NodeDatasEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata VocabularyData_NodeDatasEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_getter, &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_once,
      file_level_metadata_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto[5]);
}

// ===================================================================

VocabularyData_NodesEntry_DoNotUse::VocabularyData_NodesEntry_DoNotUse() {}
VocabularyData_NodesEntry_DoNotUse::VocabularyData_NodesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void VocabularyData_NodesEntry_DoNotUse::MergeFrom(const VocabularyData_NodesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata VocabularyData_NodesEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_getter, &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_once,
      file_level_metadata_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto[6]);
}

// ===================================================================

class VocabularyData::_Internal {
 public:
  static const ::jarvis::mapping::dbow::proto::VocabularyData_Info& info(const VocabularyData* msg);
};

const ::jarvis::mapping::dbow::proto::VocabularyData_Info&
VocabularyData::_Internal::info(const VocabularyData* msg) {
  return *msg->_impl_.info_;
}
VocabularyData::VocabularyData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &VocabularyData::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:jarvis.mapping.dbow.proto.VocabularyData)
}
VocabularyData::VocabularyData(const VocabularyData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  VocabularyData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.node_datas_)*/{}
    , /*decltype(_impl_.nodes_)*/{}
    , decltype(_impl_.word_ids_){from._impl_.word_ids_}
    , /*decltype(_impl_._word_ids_cached_byte_size_)*/{0}
    , decltype(_impl_.info_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.node_datas_.MergeFrom(from._impl_.node_datas_);
  _this->_impl_.nodes_.MergeFrom(from._impl_.nodes_);
  if (from._internal_has_info()) {
    _this->_impl_.info_ = new ::jarvis::mapping::dbow::proto::VocabularyData_Info(*from._impl_.info_);
  }
  // @@protoc_insertion_point(copy_constructor:jarvis.mapping.dbow.proto.VocabularyData)
}

inline void VocabularyData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.node_datas_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_.nodes_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_.word_ids_){arena}
    , /*decltype(_impl_._word_ids_cached_byte_size_)*/{0}
    , decltype(_impl_.info_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

VocabularyData::~VocabularyData() {
  // @@protoc_insertion_point(destructor:jarvis.mapping.dbow.proto.VocabularyData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void VocabularyData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.node_datas_.Destruct();
  _impl_.node_datas_.~MapField();
  _impl_.nodes_.Destruct();
  _impl_.nodes_.~MapField();
  _impl_.word_ids_.~RepeatedField();
  if (this != internal_default_instance()) delete _impl_.info_;
}

void VocabularyData::ArenaDtor(void* object) {
  VocabularyData* _this = reinterpret_cast< VocabularyData* >(object);
  _this->_impl_.node_datas_.Destruct();
  _this->_impl_.nodes_.Destruct();
}
void VocabularyData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void VocabularyData::Clear() {
// @@protoc_insertion_point(message_clear_start:jarvis.mapping.dbow.proto.VocabularyData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.node_datas_.Clear();
  _impl_.nodes_.Clear();
  _impl_.word_ids_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.info_ != nullptr) {
    delete _impl_.info_;
  }
  _impl_.info_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VocabularyData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .jarvis.mapping.dbow.proto.VocabularyData.Info info = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_info(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // map<uint64, .jarvis.mapping.dbow.proto.VocabularyData.NodeData> node_datas = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.node_datas_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // map<uint64, .jarvis.mapping.dbow.proto.VocabularyData.Node> nodes = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.nodes_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated uint64 word_ids = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt64Parser(_internal_mutable_word_ids(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 32) {
          _internal_add_word_ids(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* VocabularyData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:jarvis.mapping.dbow.proto.VocabularyData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .jarvis.mapping.dbow.proto.VocabularyData.Info info = 1;
  if (this->_internal_has_info()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::info(this),
        _Internal::info(this).GetCachedSize(), target, stream);
  }

  // map<uint64, .jarvis.mapping.dbow.proto.VocabularyData.NodeData> node_datas = 2;
  if (!this->_internal_node_datas().empty()) {
    using MapType = ::_pb::Map<uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_NodeData>;
    using WireHelper = VocabularyData_NodeDatasEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_node_datas();

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterFlat<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(2, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(2, entry.first, entry.second, target, stream);
      }
    }
  }

  // map<uint64, .jarvis.mapping.dbow.proto.VocabularyData.Node> nodes = 3;
  if (!this->_internal_nodes().empty()) {
    using MapType = ::_pb::Map<uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_Node>;
    using WireHelper = VocabularyData_NodesEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_nodes();

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterFlat<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
      }
    }
  }

  // repeated uint64 word_ids = 4;
  {
    int byte_size = _impl_._word_ids_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt64Packed(
          4, _internal_word_ids(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:jarvis.mapping.dbow.proto.VocabularyData)
  return target;
}

size_t VocabularyData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:jarvis.mapping.dbow.proto.VocabularyData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<uint64, .jarvis.mapping.dbow.proto.VocabularyData.NodeData> node_datas = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_node_datas_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_NodeData >::const_iterator
      it = this->_internal_node_datas().begin();
      it != this->_internal_node_datas().end(); ++it) {
    total_size += VocabularyData_NodeDatasEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // map<uint64, .jarvis.mapping.dbow.proto.VocabularyData.Node> nodes = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_nodes_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_Node >::const_iterator
      it = this->_internal_nodes().begin();
      it != this->_internal_nodes().end(); ++it) {
    total_size += VocabularyData_NodesEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // repeated uint64 word_ids = 4;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt64Size(this->_impl_.word_ids_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._word_ids_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // .jarvis.mapping.dbow.proto.VocabularyData.Info info = 1;
  if (this->_internal_has_info()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.info_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData VocabularyData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    VocabularyData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*VocabularyData::GetClassData() const { return &_class_data_; }


void VocabularyData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<VocabularyData*>(&to_msg);
  auto& from = static_cast<const VocabularyData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:jarvis.mapping.dbow.proto.VocabularyData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.node_datas_.MergeFrom(from._impl_.node_datas_);
  _this->_impl_.nodes_.MergeFrom(from._impl_.nodes_);
  _this->_impl_.word_ids_.MergeFrom(from._impl_.word_ids_);
  if (from._internal_has_info()) {
    _this->_internal_mutable_info()->::jarvis::mapping::dbow::proto::VocabularyData_Info::MergeFrom(
        from._internal_info());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void VocabularyData::CopyFrom(const VocabularyData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jarvis.mapping.dbow.proto.VocabularyData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VocabularyData::IsInitialized() const {
  return true;
}

void VocabularyData::InternalSwap(VocabularyData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.node_datas_.InternalSwap(&other->_impl_.node_datas_);
  _impl_.nodes_.InternalSwap(&other->_impl_.nodes_);
  _impl_.word_ids_.InternalSwap(&other->_impl_.word_ids_);
  swap(_impl_.info_, other->_impl_.info_);
}

::PROTOBUF_NAMESPACE_ID::Metadata VocabularyData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_getter, &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_once,
      file_level_metadata_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto[7]);
}

// ===================================================================

class VocabularyDatas::_Internal {
 public:
};

VocabularyDatas::VocabularyDatas(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:jarvis.mapping.dbow.proto.VocabularyDatas)
}
VocabularyDatas::VocabularyDatas(const VocabularyDatas& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  VocabularyDatas* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.vocabulary_datas_){from._impl_.vocabulary_datas_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:jarvis.mapping.dbow.proto.VocabularyDatas)
}

inline void VocabularyDatas::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.vocabulary_datas_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

VocabularyDatas::~VocabularyDatas() {
  // @@protoc_insertion_point(destructor:jarvis.mapping.dbow.proto.VocabularyDatas)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void VocabularyDatas::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.vocabulary_datas_.~RepeatedPtrField();
}

void VocabularyDatas::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void VocabularyDatas::Clear() {
// @@protoc_insertion_point(message_clear_start:jarvis.mapping.dbow.proto.VocabularyDatas)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.vocabulary_datas_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VocabularyDatas::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .jarvis.mapping.dbow.proto.VocabularyData vocabulary_datas = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_vocabulary_datas(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* VocabularyDatas::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:jarvis.mapping.dbow.proto.VocabularyDatas)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .jarvis.mapping.dbow.proto.VocabularyData vocabulary_datas = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_vocabulary_datas_size()); i < n; i++) {
    const auto& repfield = this->_internal_vocabulary_datas(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:jarvis.mapping.dbow.proto.VocabularyDatas)
  return target;
}

size_t VocabularyDatas::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:jarvis.mapping.dbow.proto.VocabularyDatas)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .jarvis.mapping.dbow.proto.VocabularyData vocabulary_datas = 1;
  total_size += 1UL * this->_internal_vocabulary_datas_size();
  for (const auto& msg : this->_impl_.vocabulary_datas_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData VocabularyDatas::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    VocabularyDatas::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*VocabularyDatas::GetClassData() const { return &_class_data_; }


void VocabularyDatas::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<VocabularyDatas*>(&to_msg);
  auto& from = static_cast<const VocabularyDatas&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:jarvis.mapping.dbow.proto.VocabularyDatas)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.vocabulary_datas_.MergeFrom(from._impl_.vocabulary_datas_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void VocabularyDatas::CopyFrom(const VocabularyDatas& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jarvis.mapping.dbow.proto.VocabularyDatas)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VocabularyDatas::IsInitialized() const {
  return true;
}

void VocabularyDatas::InternalSwap(VocabularyDatas* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.vocabulary_datas_.InternalSwap(&other->_impl_.vocabulary_datas_);
}

::PROTOBUF_NAMESPACE_ID::Metadata VocabularyDatas::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_getter, &descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto_once,
      file_level_metadata_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto[8]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace dbow
}  // namespace mapping
}  // namespace jarvis
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::jarvis::mapping::dbow::proto::VocabularyOption*
Arena::CreateMaybeMessage< ::jarvis::mapping::dbow::proto::VocabularyOption >(Arena* arena) {
  return Arena::CreateMessageInternal< ::jarvis::mapping::dbow::proto::VocabularyOption >(arena);
}
template<> PROTOBUF_NOINLINE ::jarvis::mapping::dbow::proto::Descriptor*
Arena::CreateMaybeMessage< ::jarvis::mapping::dbow::proto::Descriptor >(Arena* arena) {
  return Arena::CreateMessageInternal< ::jarvis::mapping::dbow::proto::Descriptor >(arena);
}
template<> PROTOBUF_NOINLINE ::jarvis::mapping::dbow::proto::VocabularyData_Node*
Arena::CreateMaybeMessage< ::jarvis::mapping::dbow::proto::VocabularyData_Node >(Arena* arena) {
  return Arena::CreateMessageInternal< ::jarvis::mapping::dbow::proto::VocabularyData_Node >(arena);
}
template<> PROTOBUF_NOINLINE ::jarvis::mapping::dbow::proto::VocabularyData_NodeData*
Arena::CreateMaybeMessage< ::jarvis::mapping::dbow::proto::VocabularyData_NodeData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::jarvis::mapping::dbow::proto::VocabularyData_NodeData >(arena);
}
template<> PROTOBUF_NOINLINE ::jarvis::mapping::dbow::proto::VocabularyData_Info*
Arena::CreateMaybeMessage< ::jarvis::mapping::dbow::proto::VocabularyData_Info >(Arena* arena) {
  return Arena::CreateMessageInternal< ::jarvis::mapping::dbow::proto::VocabularyData_Info >(arena);
}
template<> PROTOBUF_NOINLINE ::jarvis::mapping::dbow::proto::VocabularyData_NodeDatasEntry_DoNotUse*
Arena::CreateMaybeMessage< ::jarvis::mapping::dbow::proto::VocabularyData_NodeDatasEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::jarvis::mapping::dbow::proto::VocabularyData_NodeDatasEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::jarvis::mapping::dbow::proto::VocabularyData_NodesEntry_DoNotUse*
Arena::CreateMaybeMessage< ::jarvis::mapping::dbow::proto::VocabularyData_NodesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::jarvis::mapping::dbow::proto::VocabularyData_NodesEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::jarvis::mapping::dbow::proto::VocabularyData*
Arena::CreateMaybeMessage< ::jarvis::mapping::dbow::proto::VocabularyData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::jarvis::mapping::dbow::proto::VocabularyData >(arena);
}
template<> PROTOBUF_NOINLINE ::jarvis::mapping::dbow::proto::VocabularyDatas*
Arena::CreateMaybeMessage< ::jarvis::mapping::dbow::proto::VocabularyDatas >(Arena* arena) {
  return Arena::CreateMessageInternal< ::jarvis::mapping::dbow::proto::VocabularyDatas >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
