// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jarvis/mapping/dbow/proto/vocabulary_data.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto;
namespace jarvis {
namespace mapping {
namespace dbow {
namespace proto {
class Descriptor;
struct DescriptorDefaultTypeInternal;
extern DescriptorDefaultTypeInternal _Descriptor_default_instance_;
class VocabularyData;
struct VocabularyDataDefaultTypeInternal;
extern VocabularyDataDefaultTypeInternal _VocabularyData_default_instance_;
class VocabularyData_Info;
struct VocabularyData_InfoDefaultTypeInternal;
extern VocabularyData_InfoDefaultTypeInternal _VocabularyData_Info_default_instance_;
class VocabularyData_Node;
struct VocabularyData_NodeDefaultTypeInternal;
extern VocabularyData_NodeDefaultTypeInternal _VocabularyData_Node_default_instance_;
class VocabularyData_NodeData;
struct VocabularyData_NodeDataDefaultTypeInternal;
extern VocabularyData_NodeDataDefaultTypeInternal _VocabularyData_NodeData_default_instance_;
class VocabularyData_NodeDatasEntry_DoNotUse;
struct VocabularyData_NodeDatasEntry_DoNotUseDefaultTypeInternal;
extern VocabularyData_NodeDatasEntry_DoNotUseDefaultTypeInternal _VocabularyData_NodeDatasEntry_DoNotUse_default_instance_;
class VocabularyData_NodesEntry_DoNotUse;
struct VocabularyData_NodesEntry_DoNotUseDefaultTypeInternal;
extern VocabularyData_NodesEntry_DoNotUseDefaultTypeInternal _VocabularyData_NodesEntry_DoNotUse_default_instance_;
class VocabularyDatas;
struct VocabularyDatasDefaultTypeInternal;
extern VocabularyDatasDefaultTypeInternal _VocabularyDatas_default_instance_;
class VocabularyOption;
struct VocabularyOptionDefaultTypeInternal;
extern VocabularyOptionDefaultTypeInternal _VocabularyOption_default_instance_;
}  // namespace proto
}  // namespace dbow
}  // namespace mapping
}  // namespace jarvis
PROTOBUF_NAMESPACE_OPEN
template<> ::jarvis::mapping::dbow::proto::Descriptor* Arena::CreateMaybeMessage<::jarvis::mapping::dbow::proto::Descriptor>(Arena*);
template<> ::jarvis::mapping::dbow::proto::VocabularyData* Arena::CreateMaybeMessage<::jarvis::mapping::dbow::proto::VocabularyData>(Arena*);
template<> ::jarvis::mapping::dbow::proto::VocabularyData_Info* Arena::CreateMaybeMessage<::jarvis::mapping::dbow::proto::VocabularyData_Info>(Arena*);
template<> ::jarvis::mapping::dbow::proto::VocabularyData_Node* Arena::CreateMaybeMessage<::jarvis::mapping::dbow::proto::VocabularyData_Node>(Arena*);
template<> ::jarvis::mapping::dbow::proto::VocabularyData_NodeData* Arena::CreateMaybeMessage<::jarvis::mapping::dbow::proto::VocabularyData_NodeData>(Arena*);
template<> ::jarvis::mapping::dbow::proto::VocabularyData_NodeDatasEntry_DoNotUse* Arena::CreateMaybeMessage<::jarvis::mapping::dbow::proto::VocabularyData_NodeDatasEntry_DoNotUse>(Arena*);
template<> ::jarvis::mapping::dbow::proto::VocabularyData_NodesEntry_DoNotUse* Arena::CreateMaybeMessage<::jarvis::mapping::dbow::proto::VocabularyData_NodesEntry_DoNotUse>(Arena*);
template<> ::jarvis::mapping::dbow::proto::VocabularyDatas* Arena::CreateMaybeMessage<::jarvis::mapping::dbow::proto::VocabularyDatas>(Arena*);
template<> ::jarvis::mapping::dbow::proto::VocabularyOption* Arena::CreateMaybeMessage<::jarvis::mapping::dbow::proto::VocabularyOption>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace jarvis {
namespace mapping {
namespace dbow {
namespace proto {

// ===================================================================

class VocabularyOption final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:jarvis.mapping.dbow.proto.VocabularyOption) */ {
 public:
  inline VocabularyOption() : VocabularyOption(nullptr) {}
  ~VocabularyOption() override;
  explicit PROTOBUF_CONSTEXPR VocabularyOption(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VocabularyOption(const VocabularyOption& from);
  VocabularyOption(VocabularyOption&& from) noexcept
    : VocabularyOption() {
    *this = ::std::move(from);
  }

  inline VocabularyOption& operator=(const VocabularyOption& from) {
    CopyFrom(from);
    return *this;
  }
  inline VocabularyOption& operator=(VocabularyOption&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VocabularyOption& default_instance() {
    return *internal_default_instance();
  }
  static inline const VocabularyOption* internal_default_instance() {
    return reinterpret_cast<const VocabularyOption*>(
               &_VocabularyOption_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(VocabularyOption& a, VocabularyOption& b) {
    a.Swap(&b);
  }
  inline void Swap(VocabularyOption* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VocabularyOption* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VocabularyOption* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VocabularyOption>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VocabularyOption& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VocabularyOption& from) {
    VocabularyOption::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VocabularyOption* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "jarvis.mapping.dbow.proto.VocabularyOption";
  }
  protected:
  explicit VocabularyOption(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kScoreTypeFieldNumber = 1,
    kWeightingTypeFieldNumber = 2,
  };
  // uint32 score_type = 1;
  void clear_score_type();
  uint32_t score_type() const;
  void set_score_type(uint32_t value);
  private:
  uint32_t _internal_score_type() const;
  void _internal_set_score_type(uint32_t value);
  public:

  // uint32 weighting_type = 2;
  void clear_weighting_type();
  uint32_t weighting_type() const;
  void set_weighting_type(uint32_t value);
  private:
  uint32_t _internal_weighting_type() const;
  void _internal_set_weighting_type(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:jarvis.mapping.dbow.proto.VocabularyOption)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t score_type_;
    uint32_t weighting_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto;
};
// -------------------------------------------------------------------

class Descriptor final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:jarvis.mapping.dbow.proto.Descriptor) */ {
 public:
  inline Descriptor() : Descriptor(nullptr) {}
  ~Descriptor() override;
  explicit PROTOBUF_CONSTEXPR Descriptor(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Descriptor(const Descriptor& from);
  Descriptor(Descriptor&& from) noexcept
    : Descriptor() {
    *this = ::std::move(from);
  }

  inline Descriptor& operator=(const Descriptor& from) {
    CopyFrom(from);
    return *this;
  }
  inline Descriptor& operator=(Descriptor&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Descriptor& default_instance() {
    return *internal_default_instance();
  }
  static inline const Descriptor* internal_default_instance() {
    return reinterpret_cast<const Descriptor*>(
               &_Descriptor_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Descriptor& a, Descriptor& b) {
    a.Swap(&b);
  }
  inline void Swap(Descriptor* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Descriptor* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Descriptor* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Descriptor>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Descriptor& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Descriptor& from) {
    Descriptor::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Descriptor* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "jarvis.mapping.dbow.proto.Descriptor";
  }
  protected:
  explicit Descriptor(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBrifBitsetFieldNumber = 1,
  };
  // repeated uint32 brif_bitset = 1;
  int brif_bitset_size() const;
  private:
  int _internal_brif_bitset_size() const;
  public:
  void clear_brif_bitset();
  private:
  uint32_t _internal_brif_bitset(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      _internal_brif_bitset() const;
  void _internal_add_brif_bitset(uint32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      _internal_mutable_brif_bitset();
  public:
  uint32_t brif_bitset(int index) const;
  void set_brif_bitset(int index, uint32_t value);
  void add_brif_bitset(uint32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      brif_bitset() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      mutable_brif_bitset();

  // @@protoc_insertion_point(class_scope:jarvis.mapping.dbow.proto.Descriptor)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t > brif_bitset_;
    mutable std::atomic<int> _brif_bitset_cached_byte_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto;
};
// -------------------------------------------------------------------

class VocabularyData_Node final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:jarvis.mapping.dbow.proto.VocabularyData.Node) */ {
 public:
  inline VocabularyData_Node() : VocabularyData_Node(nullptr) {}
  ~VocabularyData_Node() override;
  explicit PROTOBUF_CONSTEXPR VocabularyData_Node(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VocabularyData_Node(const VocabularyData_Node& from);
  VocabularyData_Node(VocabularyData_Node&& from) noexcept
    : VocabularyData_Node() {
    *this = ::std::move(from);
  }

  inline VocabularyData_Node& operator=(const VocabularyData_Node& from) {
    CopyFrom(from);
    return *this;
  }
  inline VocabularyData_Node& operator=(VocabularyData_Node&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VocabularyData_Node& default_instance() {
    return *internal_default_instance();
  }
  static inline const VocabularyData_Node* internal_default_instance() {
    return reinterpret_cast<const VocabularyData_Node*>(
               &_VocabularyData_Node_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(VocabularyData_Node& a, VocabularyData_Node& b) {
    a.Swap(&b);
  }
  inline void Swap(VocabularyData_Node* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VocabularyData_Node* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VocabularyData_Node* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VocabularyData_Node>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VocabularyData_Node& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VocabularyData_Node& from) {
    VocabularyData_Node::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VocabularyData_Node* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "jarvis.mapping.dbow.proto.VocabularyData.Node";
  }
  protected:
  explicit VocabularyData_Node(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChildrensIdsFieldNumber = 4,
    kIdFieldNumber = 1,
    kParentIdFieldNumber = 2,
  };
  // repeated uint64 childrens_ids = 4;
  int childrens_ids_size() const;
  private:
  int _internal_childrens_ids_size() const;
  public:
  void clear_childrens_ids();
  private:
  uint64_t _internal_childrens_ids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      _internal_childrens_ids() const;
  void _internal_add_childrens_ids(uint64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      _internal_mutable_childrens_ids();
  public:
  uint64_t childrens_ids(int index) const;
  void set_childrens_ids(int index, uint64_t value);
  void add_childrens_ids(uint64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      childrens_ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      mutable_childrens_ids();

  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // uint64 parent_id = 2;
  void clear_parent_id();
  uint64_t parent_id() const;
  void set_parent_id(uint64_t value);
  private:
  uint64_t _internal_parent_id() const;
  void _internal_set_parent_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:jarvis.mapping.dbow.proto.VocabularyData.Node)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t > childrens_ids_;
    mutable std::atomic<int> _childrens_ids_cached_byte_size_;
    uint64_t id_;
    uint64_t parent_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto;
};
// -------------------------------------------------------------------

class VocabularyData_NodeData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:jarvis.mapping.dbow.proto.VocabularyData.NodeData) */ {
 public:
  inline VocabularyData_NodeData() : VocabularyData_NodeData(nullptr) {}
  ~VocabularyData_NodeData() override;
  explicit PROTOBUF_CONSTEXPR VocabularyData_NodeData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VocabularyData_NodeData(const VocabularyData_NodeData& from);
  VocabularyData_NodeData(VocabularyData_NodeData&& from) noexcept
    : VocabularyData_NodeData() {
    *this = ::std::move(from);
  }

  inline VocabularyData_NodeData& operator=(const VocabularyData_NodeData& from) {
    CopyFrom(from);
    return *this;
  }
  inline VocabularyData_NodeData& operator=(VocabularyData_NodeData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VocabularyData_NodeData& default_instance() {
    return *internal_default_instance();
  }
  static inline const VocabularyData_NodeData* internal_default_instance() {
    return reinterpret_cast<const VocabularyData_NodeData*>(
               &_VocabularyData_NodeData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(VocabularyData_NodeData& a, VocabularyData_NodeData& b) {
    a.Swap(&b);
  }
  inline void Swap(VocabularyData_NodeData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VocabularyData_NodeData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VocabularyData_NodeData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VocabularyData_NodeData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VocabularyData_NodeData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VocabularyData_NodeData& from) {
    VocabularyData_NodeData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VocabularyData_NodeData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "jarvis.mapping.dbow.proto.VocabularyData.NodeData";
  }
  protected:
  explicit VocabularyData_NodeData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDescriptorsFieldNumber = 2,
    kWeightFieldNumber = 1,
  };
  // .jarvis.mapping.dbow.proto.Descriptor descriptors = 2;
  bool has_descriptors() const;
  private:
  bool _internal_has_descriptors() const;
  public:
  void clear_descriptors();
  const ::jarvis::mapping::dbow::proto::Descriptor& descriptors() const;
  PROTOBUF_NODISCARD ::jarvis::mapping::dbow::proto::Descriptor* release_descriptors();
  ::jarvis::mapping::dbow::proto::Descriptor* mutable_descriptors();
  void set_allocated_descriptors(::jarvis::mapping::dbow::proto::Descriptor* descriptors);
  private:
  const ::jarvis::mapping::dbow::proto::Descriptor& _internal_descriptors() const;
  ::jarvis::mapping::dbow::proto::Descriptor* _internal_mutable_descriptors();
  public:
  void unsafe_arena_set_allocated_descriptors(
      ::jarvis::mapping::dbow::proto::Descriptor* descriptors);
  ::jarvis::mapping::dbow::proto::Descriptor* unsafe_arena_release_descriptors();

  // double weight = 1;
  void clear_weight();
  double weight() const;
  void set_weight(double value);
  private:
  double _internal_weight() const;
  void _internal_set_weight(double value);
  public:

  // @@protoc_insertion_point(class_scope:jarvis.mapping.dbow.proto.VocabularyData.NodeData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::jarvis::mapping::dbow::proto::Descriptor* descriptors_;
    double weight_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto;
};
// -------------------------------------------------------------------

class VocabularyData_Info final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:jarvis.mapping.dbow.proto.VocabularyData.Info) */ {
 public:
  inline VocabularyData_Info() : VocabularyData_Info(nullptr) {}
  ~VocabularyData_Info() override;
  explicit PROTOBUF_CONSTEXPR VocabularyData_Info(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VocabularyData_Info(const VocabularyData_Info& from);
  VocabularyData_Info(VocabularyData_Info&& from) noexcept
    : VocabularyData_Info() {
    *this = ::std::move(from);
  }

  inline VocabularyData_Info& operator=(const VocabularyData_Info& from) {
    CopyFrom(from);
    return *this;
  }
  inline VocabularyData_Info& operator=(VocabularyData_Info&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VocabularyData_Info& default_instance() {
    return *internal_default_instance();
  }
  static inline const VocabularyData_Info* internal_default_instance() {
    return reinterpret_cast<const VocabularyData_Info*>(
               &_VocabularyData_Info_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(VocabularyData_Info& a, VocabularyData_Info& b) {
    a.Swap(&b);
  }
  inline void Swap(VocabularyData_Info* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VocabularyData_Info* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VocabularyData_Info* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VocabularyData_Info>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VocabularyData_Info& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VocabularyData_Info& from) {
    VocabularyData_Info::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VocabularyData_Info* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "jarvis.mapping.dbow.proto.VocabularyData.Info";
  }
  protected:
  explicit VocabularyData_Info(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDescriptorTypeFieldNumber = 1,
    kOptionFieldNumber = 5,
    kDescriptorRotatedFieldNumber = 2,
    kBranchingFactorFieldNumber = 3,
    kDepthLevelsFieldNumber = 4,
  };
  // string descriptor_type = 1;
  void clear_descriptor_type();
  const std::string& descriptor_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_descriptor_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_descriptor_type();
  PROTOBUF_NODISCARD std::string* release_descriptor_type();
  void set_allocated_descriptor_type(std::string* descriptor_type);
  private:
  const std::string& _internal_descriptor_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_descriptor_type(const std::string& value);
  std::string* _internal_mutable_descriptor_type();
  public:

  // .jarvis.mapping.dbow.proto.VocabularyOption option = 5;
  bool has_option() const;
  private:
  bool _internal_has_option() const;
  public:
  void clear_option();
  const ::jarvis::mapping::dbow::proto::VocabularyOption& option() const;
  PROTOBUF_NODISCARD ::jarvis::mapping::dbow::proto::VocabularyOption* release_option();
  ::jarvis::mapping::dbow::proto::VocabularyOption* mutable_option();
  void set_allocated_option(::jarvis::mapping::dbow::proto::VocabularyOption* option);
  private:
  const ::jarvis::mapping::dbow::proto::VocabularyOption& _internal_option() const;
  ::jarvis::mapping::dbow::proto::VocabularyOption* _internal_mutable_option();
  public:
  void unsafe_arena_set_allocated_option(
      ::jarvis::mapping::dbow::proto::VocabularyOption* option);
  ::jarvis::mapping::dbow::proto::VocabularyOption* unsafe_arena_release_option();

  // int32 descriptor_rotated = 2;
  void clear_descriptor_rotated();
  int32_t descriptor_rotated() const;
  void set_descriptor_rotated(int32_t value);
  private:
  int32_t _internal_descriptor_rotated() const;
  void _internal_set_descriptor_rotated(int32_t value);
  public:

  // int32 branching_factor = 3;
  void clear_branching_factor();
  int32_t branching_factor() const;
  void set_branching_factor(int32_t value);
  private:
  int32_t _internal_branching_factor() const;
  void _internal_set_branching_factor(int32_t value);
  public:

  // int32 depth_levels = 4;
  void clear_depth_levels();
  int32_t depth_levels() const;
  void set_depth_levels(int32_t value);
  private:
  int32_t _internal_depth_levels() const;
  void _internal_set_depth_levels(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:jarvis.mapping.dbow.proto.VocabularyData.Info)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr descriptor_type_;
    ::jarvis::mapping::dbow::proto::VocabularyOption* option_;
    int32_t descriptor_rotated_;
    int32_t branching_factor_;
    int32_t depth_levels_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto;
};
// -------------------------------------------------------------------

class VocabularyData_NodeDatasEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<VocabularyData_NodeDatasEntry_DoNotUse, 
    uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_NodeData,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<VocabularyData_NodeDatasEntry_DoNotUse, 
    uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_NodeData,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  VocabularyData_NodeDatasEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR VocabularyData_NodeDatasEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit VocabularyData_NodeDatasEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const VocabularyData_NodeDatasEntry_DoNotUse& other);
  static const VocabularyData_NodeDatasEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const VocabularyData_NodeDatasEntry_DoNotUse*>(&_VocabularyData_NodeDatasEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto;
};

// -------------------------------------------------------------------

class VocabularyData_NodesEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<VocabularyData_NodesEntry_DoNotUse, 
    uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_Node,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<VocabularyData_NodesEntry_DoNotUse, 
    uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_Node,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  VocabularyData_NodesEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR VocabularyData_NodesEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit VocabularyData_NodesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const VocabularyData_NodesEntry_DoNotUse& other);
  static const VocabularyData_NodesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const VocabularyData_NodesEntry_DoNotUse*>(&_VocabularyData_NodesEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto;
};

// -------------------------------------------------------------------

class VocabularyData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:jarvis.mapping.dbow.proto.VocabularyData) */ {
 public:
  inline VocabularyData() : VocabularyData(nullptr) {}
  ~VocabularyData() override;
  explicit PROTOBUF_CONSTEXPR VocabularyData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VocabularyData(const VocabularyData& from);
  VocabularyData(VocabularyData&& from) noexcept
    : VocabularyData() {
    *this = ::std::move(from);
  }

  inline VocabularyData& operator=(const VocabularyData& from) {
    CopyFrom(from);
    return *this;
  }
  inline VocabularyData& operator=(VocabularyData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VocabularyData& default_instance() {
    return *internal_default_instance();
  }
  static inline const VocabularyData* internal_default_instance() {
    return reinterpret_cast<const VocabularyData*>(
               &_VocabularyData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(VocabularyData& a, VocabularyData& b) {
    a.Swap(&b);
  }
  inline void Swap(VocabularyData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VocabularyData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VocabularyData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VocabularyData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VocabularyData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VocabularyData& from) {
    VocabularyData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VocabularyData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "jarvis.mapping.dbow.proto.VocabularyData";
  }
  protected:
  explicit VocabularyData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef VocabularyData_Node Node;
  typedef VocabularyData_NodeData NodeData;
  typedef VocabularyData_Info Info;

  // accessors -------------------------------------------------------

  enum : int {
    kNodeDatasFieldNumber = 2,
    kNodesFieldNumber = 3,
    kWordIdsFieldNumber = 4,
    kInfoFieldNumber = 1,
  };
  // map<uint64, .jarvis.mapping.dbow.proto.VocabularyData.NodeData> node_datas = 2;
  int node_datas_size() const;
  private:
  int _internal_node_datas_size() const;
  public:
  void clear_node_datas();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_NodeData >&
      _internal_node_datas() const;
  ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_NodeData >*
      _internal_mutable_node_datas();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_NodeData >&
      node_datas() const;
  ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_NodeData >*
      mutable_node_datas();

  // map<uint64, .jarvis.mapping.dbow.proto.VocabularyData.Node> nodes = 3;
  int nodes_size() const;
  private:
  int _internal_nodes_size() const;
  public:
  void clear_nodes();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_Node >&
      _internal_nodes() const;
  ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_Node >*
      _internal_mutable_nodes();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_Node >&
      nodes() const;
  ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_Node >*
      mutable_nodes();

  // repeated uint64 word_ids = 4;
  int word_ids_size() const;
  private:
  int _internal_word_ids_size() const;
  public:
  void clear_word_ids();
  private:
  uint64_t _internal_word_ids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      _internal_word_ids() const;
  void _internal_add_word_ids(uint64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      _internal_mutable_word_ids();
  public:
  uint64_t word_ids(int index) const;
  void set_word_ids(int index, uint64_t value);
  void add_word_ids(uint64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      word_ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      mutable_word_ids();

  // .jarvis.mapping.dbow.proto.VocabularyData.Info info = 1;
  bool has_info() const;
  private:
  bool _internal_has_info() const;
  public:
  void clear_info();
  const ::jarvis::mapping::dbow::proto::VocabularyData_Info& info() const;
  PROTOBUF_NODISCARD ::jarvis::mapping::dbow::proto::VocabularyData_Info* release_info();
  ::jarvis::mapping::dbow::proto::VocabularyData_Info* mutable_info();
  void set_allocated_info(::jarvis::mapping::dbow::proto::VocabularyData_Info* info);
  private:
  const ::jarvis::mapping::dbow::proto::VocabularyData_Info& _internal_info() const;
  ::jarvis::mapping::dbow::proto::VocabularyData_Info* _internal_mutable_info();
  public:
  void unsafe_arena_set_allocated_info(
      ::jarvis::mapping::dbow::proto::VocabularyData_Info* info);
  ::jarvis::mapping::dbow::proto::VocabularyData_Info* unsafe_arena_release_info();

  // @@protoc_insertion_point(class_scope:jarvis.mapping.dbow.proto.VocabularyData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        VocabularyData_NodeDatasEntry_DoNotUse,
        uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_NodeData,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> node_datas_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        VocabularyData_NodesEntry_DoNotUse,
        uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_Node,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> nodes_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t > word_ids_;
    mutable std::atomic<int> _word_ids_cached_byte_size_;
    ::jarvis::mapping::dbow::proto::VocabularyData_Info* info_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto;
};
// -------------------------------------------------------------------

class VocabularyDatas final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:jarvis.mapping.dbow.proto.VocabularyDatas) */ {
 public:
  inline VocabularyDatas() : VocabularyDatas(nullptr) {}
  ~VocabularyDatas() override;
  explicit PROTOBUF_CONSTEXPR VocabularyDatas(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VocabularyDatas(const VocabularyDatas& from);
  VocabularyDatas(VocabularyDatas&& from) noexcept
    : VocabularyDatas() {
    *this = ::std::move(from);
  }

  inline VocabularyDatas& operator=(const VocabularyDatas& from) {
    CopyFrom(from);
    return *this;
  }
  inline VocabularyDatas& operator=(VocabularyDatas&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VocabularyDatas& default_instance() {
    return *internal_default_instance();
  }
  static inline const VocabularyDatas* internal_default_instance() {
    return reinterpret_cast<const VocabularyDatas*>(
               &_VocabularyDatas_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(VocabularyDatas& a, VocabularyDatas& b) {
    a.Swap(&b);
  }
  inline void Swap(VocabularyDatas* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VocabularyDatas* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VocabularyDatas* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VocabularyDatas>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VocabularyDatas& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VocabularyDatas& from) {
    VocabularyDatas::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VocabularyDatas* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "jarvis.mapping.dbow.proto.VocabularyDatas";
  }
  protected:
  explicit VocabularyDatas(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVocabularyDatasFieldNumber = 1,
  };
  // repeated .jarvis.mapping.dbow.proto.VocabularyData vocabulary_datas = 1;
  int vocabulary_datas_size() const;
  private:
  int _internal_vocabulary_datas_size() const;
  public:
  void clear_vocabulary_datas();
  ::jarvis::mapping::dbow::proto::VocabularyData* mutable_vocabulary_datas(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::jarvis::mapping::dbow::proto::VocabularyData >*
      mutable_vocabulary_datas();
  private:
  const ::jarvis::mapping::dbow::proto::VocabularyData& _internal_vocabulary_datas(int index) const;
  ::jarvis::mapping::dbow::proto::VocabularyData* _internal_add_vocabulary_datas();
  public:
  const ::jarvis::mapping::dbow::proto::VocabularyData& vocabulary_datas(int index) const;
  ::jarvis::mapping::dbow::proto::VocabularyData* add_vocabulary_datas();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::jarvis::mapping::dbow::proto::VocabularyData >&
      vocabulary_datas() const;

  // @@protoc_insertion_point(class_scope:jarvis.mapping.dbow.proto.VocabularyDatas)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::jarvis::mapping::dbow::proto::VocabularyData > vocabulary_datas_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VocabularyOption

// uint32 score_type = 1;
inline void VocabularyOption::clear_score_type() {
  _impl_.score_type_ = 0u;
}
inline uint32_t VocabularyOption::_internal_score_type() const {
  return _impl_.score_type_;
}
inline uint32_t VocabularyOption::score_type() const {
  // @@protoc_insertion_point(field_get:jarvis.mapping.dbow.proto.VocabularyOption.score_type)
  return _internal_score_type();
}
inline void VocabularyOption::_internal_set_score_type(uint32_t value) {
  
  _impl_.score_type_ = value;
}
inline void VocabularyOption::set_score_type(uint32_t value) {
  _internal_set_score_type(value);
  // @@protoc_insertion_point(field_set:jarvis.mapping.dbow.proto.VocabularyOption.score_type)
}

// uint32 weighting_type = 2;
inline void VocabularyOption::clear_weighting_type() {
  _impl_.weighting_type_ = 0u;
}
inline uint32_t VocabularyOption::_internal_weighting_type() const {
  return _impl_.weighting_type_;
}
inline uint32_t VocabularyOption::weighting_type() const {
  // @@protoc_insertion_point(field_get:jarvis.mapping.dbow.proto.VocabularyOption.weighting_type)
  return _internal_weighting_type();
}
inline void VocabularyOption::_internal_set_weighting_type(uint32_t value) {
  
  _impl_.weighting_type_ = value;
}
inline void VocabularyOption::set_weighting_type(uint32_t value) {
  _internal_set_weighting_type(value);
  // @@protoc_insertion_point(field_set:jarvis.mapping.dbow.proto.VocabularyOption.weighting_type)
}

// -------------------------------------------------------------------

// Descriptor

// repeated uint32 brif_bitset = 1;
inline int Descriptor::_internal_brif_bitset_size() const {
  return _impl_.brif_bitset_.size();
}
inline int Descriptor::brif_bitset_size() const {
  return _internal_brif_bitset_size();
}
inline void Descriptor::clear_brif_bitset() {
  _impl_.brif_bitset_.Clear();
}
inline uint32_t Descriptor::_internal_brif_bitset(int index) const {
  return _impl_.brif_bitset_.Get(index);
}
inline uint32_t Descriptor::brif_bitset(int index) const {
  // @@protoc_insertion_point(field_get:jarvis.mapping.dbow.proto.Descriptor.brif_bitset)
  return _internal_brif_bitset(index);
}
inline void Descriptor::set_brif_bitset(int index, uint32_t value) {
  _impl_.brif_bitset_.Set(index, value);
  // @@protoc_insertion_point(field_set:jarvis.mapping.dbow.proto.Descriptor.brif_bitset)
}
inline void Descriptor::_internal_add_brif_bitset(uint32_t value) {
  _impl_.brif_bitset_.Add(value);
}
inline void Descriptor::add_brif_bitset(uint32_t value) {
  _internal_add_brif_bitset(value);
  // @@protoc_insertion_point(field_add:jarvis.mapping.dbow.proto.Descriptor.brif_bitset)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
Descriptor::_internal_brif_bitset() const {
  return _impl_.brif_bitset_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
Descriptor::brif_bitset() const {
  // @@protoc_insertion_point(field_list:jarvis.mapping.dbow.proto.Descriptor.brif_bitset)
  return _internal_brif_bitset();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
Descriptor::_internal_mutable_brif_bitset() {
  return &_impl_.brif_bitset_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
Descriptor::mutable_brif_bitset() {
  // @@protoc_insertion_point(field_mutable_list:jarvis.mapping.dbow.proto.Descriptor.brif_bitset)
  return _internal_mutable_brif_bitset();
}

// -------------------------------------------------------------------

// VocabularyData_Node

// uint64 id = 1;
inline void VocabularyData_Node::clear_id() {
  _impl_.id_ = uint64_t{0u};
}
inline uint64_t VocabularyData_Node::_internal_id() const {
  return _impl_.id_;
}
inline uint64_t VocabularyData_Node::id() const {
  // @@protoc_insertion_point(field_get:jarvis.mapping.dbow.proto.VocabularyData.Node.id)
  return _internal_id();
}
inline void VocabularyData_Node::_internal_set_id(uint64_t value) {
  
  _impl_.id_ = value;
}
inline void VocabularyData_Node::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:jarvis.mapping.dbow.proto.VocabularyData.Node.id)
}

// uint64 parent_id = 2;
inline void VocabularyData_Node::clear_parent_id() {
  _impl_.parent_id_ = uint64_t{0u};
}
inline uint64_t VocabularyData_Node::_internal_parent_id() const {
  return _impl_.parent_id_;
}
inline uint64_t VocabularyData_Node::parent_id() const {
  // @@protoc_insertion_point(field_get:jarvis.mapping.dbow.proto.VocabularyData.Node.parent_id)
  return _internal_parent_id();
}
inline void VocabularyData_Node::_internal_set_parent_id(uint64_t value) {
  
  _impl_.parent_id_ = value;
}
inline void VocabularyData_Node::set_parent_id(uint64_t value) {
  _internal_set_parent_id(value);
  // @@protoc_insertion_point(field_set:jarvis.mapping.dbow.proto.VocabularyData.Node.parent_id)
}

// repeated uint64 childrens_ids = 4;
inline int VocabularyData_Node::_internal_childrens_ids_size() const {
  return _impl_.childrens_ids_.size();
}
inline int VocabularyData_Node::childrens_ids_size() const {
  return _internal_childrens_ids_size();
}
inline void VocabularyData_Node::clear_childrens_ids() {
  _impl_.childrens_ids_.Clear();
}
inline uint64_t VocabularyData_Node::_internal_childrens_ids(int index) const {
  return _impl_.childrens_ids_.Get(index);
}
inline uint64_t VocabularyData_Node::childrens_ids(int index) const {
  // @@protoc_insertion_point(field_get:jarvis.mapping.dbow.proto.VocabularyData.Node.childrens_ids)
  return _internal_childrens_ids(index);
}
inline void VocabularyData_Node::set_childrens_ids(int index, uint64_t value) {
  _impl_.childrens_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:jarvis.mapping.dbow.proto.VocabularyData.Node.childrens_ids)
}
inline void VocabularyData_Node::_internal_add_childrens_ids(uint64_t value) {
  _impl_.childrens_ids_.Add(value);
}
inline void VocabularyData_Node::add_childrens_ids(uint64_t value) {
  _internal_add_childrens_ids(value);
  // @@protoc_insertion_point(field_add:jarvis.mapping.dbow.proto.VocabularyData.Node.childrens_ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
VocabularyData_Node::_internal_childrens_ids() const {
  return _impl_.childrens_ids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
VocabularyData_Node::childrens_ids() const {
  // @@protoc_insertion_point(field_list:jarvis.mapping.dbow.proto.VocabularyData.Node.childrens_ids)
  return _internal_childrens_ids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
VocabularyData_Node::_internal_mutable_childrens_ids() {
  return &_impl_.childrens_ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
VocabularyData_Node::mutable_childrens_ids() {
  // @@protoc_insertion_point(field_mutable_list:jarvis.mapping.dbow.proto.VocabularyData.Node.childrens_ids)
  return _internal_mutable_childrens_ids();
}

// -------------------------------------------------------------------

// VocabularyData_NodeData

// double weight = 1;
inline void VocabularyData_NodeData::clear_weight() {
  _impl_.weight_ = 0;
}
inline double VocabularyData_NodeData::_internal_weight() const {
  return _impl_.weight_;
}
inline double VocabularyData_NodeData::weight() const {
  // @@protoc_insertion_point(field_get:jarvis.mapping.dbow.proto.VocabularyData.NodeData.weight)
  return _internal_weight();
}
inline void VocabularyData_NodeData::_internal_set_weight(double value) {
  
  _impl_.weight_ = value;
}
inline void VocabularyData_NodeData::set_weight(double value) {
  _internal_set_weight(value);
  // @@protoc_insertion_point(field_set:jarvis.mapping.dbow.proto.VocabularyData.NodeData.weight)
}

// .jarvis.mapping.dbow.proto.Descriptor descriptors = 2;
inline bool VocabularyData_NodeData::_internal_has_descriptors() const {
  return this != internal_default_instance() && _impl_.descriptors_ != nullptr;
}
inline bool VocabularyData_NodeData::has_descriptors() const {
  return _internal_has_descriptors();
}
inline void VocabularyData_NodeData::clear_descriptors() {
  if (GetArenaForAllocation() == nullptr && _impl_.descriptors_ != nullptr) {
    delete _impl_.descriptors_;
  }
  _impl_.descriptors_ = nullptr;
}
inline const ::jarvis::mapping::dbow::proto::Descriptor& VocabularyData_NodeData::_internal_descriptors() const {
  const ::jarvis::mapping::dbow::proto::Descriptor* p = _impl_.descriptors_;
  return p != nullptr ? *p : reinterpret_cast<const ::jarvis::mapping::dbow::proto::Descriptor&>(
      ::jarvis::mapping::dbow::proto::_Descriptor_default_instance_);
}
inline const ::jarvis::mapping::dbow::proto::Descriptor& VocabularyData_NodeData::descriptors() const {
  // @@protoc_insertion_point(field_get:jarvis.mapping.dbow.proto.VocabularyData.NodeData.descriptors)
  return _internal_descriptors();
}
inline void VocabularyData_NodeData::unsafe_arena_set_allocated_descriptors(
    ::jarvis::mapping::dbow::proto::Descriptor* descriptors) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.descriptors_);
  }
  _impl_.descriptors_ = descriptors;
  if (descriptors) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:jarvis.mapping.dbow.proto.VocabularyData.NodeData.descriptors)
}
inline ::jarvis::mapping::dbow::proto::Descriptor* VocabularyData_NodeData::release_descriptors() {
  
  ::jarvis::mapping::dbow::proto::Descriptor* temp = _impl_.descriptors_;
  _impl_.descriptors_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::jarvis::mapping::dbow::proto::Descriptor* VocabularyData_NodeData::unsafe_arena_release_descriptors() {
  // @@protoc_insertion_point(field_release:jarvis.mapping.dbow.proto.VocabularyData.NodeData.descriptors)
  
  ::jarvis::mapping::dbow::proto::Descriptor* temp = _impl_.descriptors_;
  _impl_.descriptors_ = nullptr;
  return temp;
}
inline ::jarvis::mapping::dbow::proto::Descriptor* VocabularyData_NodeData::_internal_mutable_descriptors() {
  
  if (_impl_.descriptors_ == nullptr) {
    auto* p = CreateMaybeMessage<::jarvis::mapping::dbow::proto::Descriptor>(GetArenaForAllocation());
    _impl_.descriptors_ = p;
  }
  return _impl_.descriptors_;
}
inline ::jarvis::mapping::dbow::proto::Descriptor* VocabularyData_NodeData::mutable_descriptors() {
  ::jarvis::mapping::dbow::proto::Descriptor* _msg = _internal_mutable_descriptors();
  // @@protoc_insertion_point(field_mutable:jarvis.mapping.dbow.proto.VocabularyData.NodeData.descriptors)
  return _msg;
}
inline void VocabularyData_NodeData::set_allocated_descriptors(::jarvis::mapping::dbow::proto::Descriptor* descriptors) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.descriptors_;
  }
  if (descriptors) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(descriptors);
    if (message_arena != submessage_arena) {
      descriptors = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, descriptors, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.descriptors_ = descriptors;
  // @@protoc_insertion_point(field_set_allocated:jarvis.mapping.dbow.proto.VocabularyData.NodeData.descriptors)
}

// -------------------------------------------------------------------

// VocabularyData_Info

// string descriptor_type = 1;
inline void VocabularyData_Info::clear_descriptor_type() {
  _impl_.descriptor_type_.ClearToEmpty();
}
inline const std::string& VocabularyData_Info::descriptor_type() const {
  // @@protoc_insertion_point(field_get:jarvis.mapping.dbow.proto.VocabularyData.Info.descriptor_type)
  return _internal_descriptor_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VocabularyData_Info::set_descriptor_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.descriptor_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:jarvis.mapping.dbow.proto.VocabularyData.Info.descriptor_type)
}
inline std::string* VocabularyData_Info::mutable_descriptor_type() {
  std::string* _s = _internal_mutable_descriptor_type();
  // @@protoc_insertion_point(field_mutable:jarvis.mapping.dbow.proto.VocabularyData.Info.descriptor_type)
  return _s;
}
inline const std::string& VocabularyData_Info::_internal_descriptor_type() const {
  return _impl_.descriptor_type_.Get();
}
inline void VocabularyData_Info::_internal_set_descriptor_type(const std::string& value) {
  
  _impl_.descriptor_type_.Set(value, GetArenaForAllocation());
}
inline std::string* VocabularyData_Info::_internal_mutable_descriptor_type() {
  
  return _impl_.descriptor_type_.Mutable(GetArenaForAllocation());
}
inline std::string* VocabularyData_Info::release_descriptor_type() {
  // @@protoc_insertion_point(field_release:jarvis.mapping.dbow.proto.VocabularyData.Info.descriptor_type)
  return _impl_.descriptor_type_.Release();
}
inline void VocabularyData_Info::set_allocated_descriptor_type(std::string* descriptor_type) {
  if (descriptor_type != nullptr) {
    
  } else {
    
  }
  _impl_.descriptor_type_.SetAllocated(descriptor_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.descriptor_type_.IsDefault()) {
    _impl_.descriptor_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:jarvis.mapping.dbow.proto.VocabularyData.Info.descriptor_type)
}

// int32 descriptor_rotated = 2;
inline void VocabularyData_Info::clear_descriptor_rotated() {
  _impl_.descriptor_rotated_ = 0;
}
inline int32_t VocabularyData_Info::_internal_descriptor_rotated() const {
  return _impl_.descriptor_rotated_;
}
inline int32_t VocabularyData_Info::descriptor_rotated() const {
  // @@protoc_insertion_point(field_get:jarvis.mapping.dbow.proto.VocabularyData.Info.descriptor_rotated)
  return _internal_descriptor_rotated();
}
inline void VocabularyData_Info::_internal_set_descriptor_rotated(int32_t value) {
  
  _impl_.descriptor_rotated_ = value;
}
inline void VocabularyData_Info::set_descriptor_rotated(int32_t value) {
  _internal_set_descriptor_rotated(value);
  // @@protoc_insertion_point(field_set:jarvis.mapping.dbow.proto.VocabularyData.Info.descriptor_rotated)
}

// int32 branching_factor = 3;
inline void VocabularyData_Info::clear_branching_factor() {
  _impl_.branching_factor_ = 0;
}
inline int32_t VocabularyData_Info::_internal_branching_factor() const {
  return _impl_.branching_factor_;
}
inline int32_t VocabularyData_Info::branching_factor() const {
  // @@protoc_insertion_point(field_get:jarvis.mapping.dbow.proto.VocabularyData.Info.branching_factor)
  return _internal_branching_factor();
}
inline void VocabularyData_Info::_internal_set_branching_factor(int32_t value) {
  
  _impl_.branching_factor_ = value;
}
inline void VocabularyData_Info::set_branching_factor(int32_t value) {
  _internal_set_branching_factor(value);
  // @@protoc_insertion_point(field_set:jarvis.mapping.dbow.proto.VocabularyData.Info.branching_factor)
}

// int32 depth_levels = 4;
inline void VocabularyData_Info::clear_depth_levels() {
  _impl_.depth_levels_ = 0;
}
inline int32_t VocabularyData_Info::_internal_depth_levels() const {
  return _impl_.depth_levels_;
}
inline int32_t VocabularyData_Info::depth_levels() const {
  // @@protoc_insertion_point(field_get:jarvis.mapping.dbow.proto.VocabularyData.Info.depth_levels)
  return _internal_depth_levels();
}
inline void VocabularyData_Info::_internal_set_depth_levels(int32_t value) {
  
  _impl_.depth_levels_ = value;
}
inline void VocabularyData_Info::set_depth_levels(int32_t value) {
  _internal_set_depth_levels(value);
  // @@protoc_insertion_point(field_set:jarvis.mapping.dbow.proto.VocabularyData.Info.depth_levels)
}

// .jarvis.mapping.dbow.proto.VocabularyOption option = 5;
inline bool VocabularyData_Info::_internal_has_option() const {
  return this != internal_default_instance() && _impl_.option_ != nullptr;
}
inline bool VocabularyData_Info::has_option() const {
  return _internal_has_option();
}
inline void VocabularyData_Info::clear_option() {
  if (GetArenaForAllocation() == nullptr && _impl_.option_ != nullptr) {
    delete _impl_.option_;
  }
  _impl_.option_ = nullptr;
}
inline const ::jarvis::mapping::dbow::proto::VocabularyOption& VocabularyData_Info::_internal_option() const {
  const ::jarvis::mapping::dbow::proto::VocabularyOption* p = _impl_.option_;
  return p != nullptr ? *p : reinterpret_cast<const ::jarvis::mapping::dbow::proto::VocabularyOption&>(
      ::jarvis::mapping::dbow::proto::_VocabularyOption_default_instance_);
}
inline const ::jarvis::mapping::dbow::proto::VocabularyOption& VocabularyData_Info::option() const {
  // @@protoc_insertion_point(field_get:jarvis.mapping.dbow.proto.VocabularyData.Info.option)
  return _internal_option();
}
inline void VocabularyData_Info::unsafe_arena_set_allocated_option(
    ::jarvis::mapping::dbow::proto::VocabularyOption* option) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.option_);
  }
  _impl_.option_ = option;
  if (option) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:jarvis.mapping.dbow.proto.VocabularyData.Info.option)
}
inline ::jarvis::mapping::dbow::proto::VocabularyOption* VocabularyData_Info::release_option() {
  
  ::jarvis::mapping::dbow::proto::VocabularyOption* temp = _impl_.option_;
  _impl_.option_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::jarvis::mapping::dbow::proto::VocabularyOption* VocabularyData_Info::unsafe_arena_release_option() {
  // @@protoc_insertion_point(field_release:jarvis.mapping.dbow.proto.VocabularyData.Info.option)
  
  ::jarvis::mapping::dbow::proto::VocabularyOption* temp = _impl_.option_;
  _impl_.option_ = nullptr;
  return temp;
}
inline ::jarvis::mapping::dbow::proto::VocabularyOption* VocabularyData_Info::_internal_mutable_option() {
  
  if (_impl_.option_ == nullptr) {
    auto* p = CreateMaybeMessage<::jarvis::mapping::dbow::proto::VocabularyOption>(GetArenaForAllocation());
    _impl_.option_ = p;
  }
  return _impl_.option_;
}
inline ::jarvis::mapping::dbow::proto::VocabularyOption* VocabularyData_Info::mutable_option() {
  ::jarvis::mapping::dbow::proto::VocabularyOption* _msg = _internal_mutable_option();
  // @@protoc_insertion_point(field_mutable:jarvis.mapping.dbow.proto.VocabularyData.Info.option)
  return _msg;
}
inline void VocabularyData_Info::set_allocated_option(::jarvis::mapping::dbow::proto::VocabularyOption* option) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.option_;
  }
  if (option) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(option);
    if (message_arena != submessage_arena) {
      option = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, option, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.option_ = option;
  // @@protoc_insertion_point(field_set_allocated:jarvis.mapping.dbow.proto.VocabularyData.Info.option)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// VocabularyData

// .jarvis.mapping.dbow.proto.VocabularyData.Info info = 1;
inline bool VocabularyData::_internal_has_info() const {
  return this != internal_default_instance() && _impl_.info_ != nullptr;
}
inline bool VocabularyData::has_info() const {
  return _internal_has_info();
}
inline void VocabularyData::clear_info() {
  if (GetArenaForAllocation() == nullptr && _impl_.info_ != nullptr) {
    delete _impl_.info_;
  }
  _impl_.info_ = nullptr;
}
inline const ::jarvis::mapping::dbow::proto::VocabularyData_Info& VocabularyData::_internal_info() const {
  const ::jarvis::mapping::dbow::proto::VocabularyData_Info* p = _impl_.info_;
  return p != nullptr ? *p : reinterpret_cast<const ::jarvis::mapping::dbow::proto::VocabularyData_Info&>(
      ::jarvis::mapping::dbow::proto::_VocabularyData_Info_default_instance_);
}
inline const ::jarvis::mapping::dbow::proto::VocabularyData_Info& VocabularyData::info() const {
  // @@protoc_insertion_point(field_get:jarvis.mapping.dbow.proto.VocabularyData.info)
  return _internal_info();
}
inline void VocabularyData::unsafe_arena_set_allocated_info(
    ::jarvis::mapping::dbow::proto::VocabularyData_Info* info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.info_);
  }
  _impl_.info_ = info;
  if (info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:jarvis.mapping.dbow.proto.VocabularyData.info)
}
inline ::jarvis::mapping::dbow::proto::VocabularyData_Info* VocabularyData::release_info() {
  
  ::jarvis::mapping::dbow::proto::VocabularyData_Info* temp = _impl_.info_;
  _impl_.info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::jarvis::mapping::dbow::proto::VocabularyData_Info* VocabularyData::unsafe_arena_release_info() {
  // @@protoc_insertion_point(field_release:jarvis.mapping.dbow.proto.VocabularyData.info)
  
  ::jarvis::mapping::dbow::proto::VocabularyData_Info* temp = _impl_.info_;
  _impl_.info_ = nullptr;
  return temp;
}
inline ::jarvis::mapping::dbow::proto::VocabularyData_Info* VocabularyData::_internal_mutable_info() {
  
  if (_impl_.info_ == nullptr) {
    auto* p = CreateMaybeMessage<::jarvis::mapping::dbow::proto::VocabularyData_Info>(GetArenaForAllocation());
    _impl_.info_ = p;
  }
  return _impl_.info_;
}
inline ::jarvis::mapping::dbow::proto::VocabularyData_Info* VocabularyData::mutable_info() {
  ::jarvis::mapping::dbow::proto::VocabularyData_Info* _msg = _internal_mutable_info();
  // @@protoc_insertion_point(field_mutable:jarvis.mapping.dbow.proto.VocabularyData.info)
  return _msg;
}
inline void VocabularyData::set_allocated_info(::jarvis::mapping::dbow::proto::VocabularyData_Info* info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.info_;
  }
  if (info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(info);
    if (message_arena != submessage_arena) {
      info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, info, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.info_ = info;
  // @@protoc_insertion_point(field_set_allocated:jarvis.mapping.dbow.proto.VocabularyData.info)
}

// map<uint64, .jarvis.mapping.dbow.proto.VocabularyData.NodeData> node_datas = 2;
inline int VocabularyData::_internal_node_datas_size() const {
  return _impl_.node_datas_.size();
}
inline int VocabularyData::node_datas_size() const {
  return _internal_node_datas_size();
}
inline void VocabularyData::clear_node_datas() {
  _impl_.node_datas_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_NodeData >&
VocabularyData::_internal_node_datas() const {
  return _impl_.node_datas_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_NodeData >&
VocabularyData::node_datas() const {
  // @@protoc_insertion_point(field_map:jarvis.mapping.dbow.proto.VocabularyData.node_datas)
  return _internal_node_datas();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_NodeData >*
VocabularyData::_internal_mutable_node_datas() {
  return _impl_.node_datas_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_NodeData >*
VocabularyData::mutable_node_datas() {
  // @@protoc_insertion_point(field_mutable_map:jarvis.mapping.dbow.proto.VocabularyData.node_datas)
  return _internal_mutable_node_datas();
}

// map<uint64, .jarvis.mapping.dbow.proto.VocabularyData.Node> nodes = 3;
inline int VocabularyData::_internal_nodes_size() const {
  return _impl_.nodes_.size();
}
inline int VocabularyData::nodes_size() const {
  return _internal_nodes_size();
}
inline void VocabularyData::clear_nodes() {
  _impl_.nodes_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_Node >&
VocabularyData::_internal_nodes() const {
  return _impl_.nodes_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_Node >&
VocabularyData::nodes() const {
  // @@protoc_insertion_point(field_map:jarvis.mapping.dbow.proto.VocabularyData.nodes)
  return _internal_nodes();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_Node >*
VocabularyData::_internal_mutable_nodes() {
  return _impl_.nodes_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::jarvis::mapping::dbow::proto::VocabularyData_Node >*
VocabularyData::mutable_nodes() {
  // @@protoc_insertion_point(field_mutable_map:jarvis.mapping.dbow.proto.VocabularyData.nodes)
  return _internal_mutable_nodes();
}

// repeated uint64 word_ids = 4;
inline int VocabularyData::_internal_word_ids_size() const {
  return _impl_.word_ids_.size();
}
inline int VocabularyData::word_ids_size() const {
  return _internal_word_ids_size();
}
inline void VocabularyData::clear_word_ids() {
  _impl_.word_ids_.Clear();
}
inline uint64_t VocabularyData::_internal_word_ids(int index) const {
  return _impl_.word_ids_.Get(index);
}
inline uint64_t VocabularyData::word_ids(int index) const {
  // @@protoc_insertion_point(field_get:jarvis.mapping.dbow.proto.VocabularyData.word_ids)
  return _internal_word_ids(index);
}
inline void VocabularyData::set_word_ids(int index, uint64_t value) {
  _impl_.word_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:jarvis.mapping.dbow.proto.VocabularyData.word_ids)
}
inline void VocabularyData::_internal_add_word_ids(uint64_t value) {
  _impl_.word_ids_.Add(value);
}
inline void VocabularyData::add_word_ids(uint64_t value) {
  _internal_add_word_ids(value);
  // @@protoc_insertion_point(field_add:jarvis.mapping.dbow.proto.VocabularyData.word_ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
VocabularyData::_internal_word_ids() const {
  return _impl_.word_ids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
VocabularyData::word_ids() const {
  // @@protoc_insertion_point(field_list:jarvis.mapping.dbow.proto.VocabularyData.word_ids)
  return _internal_word_ids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
VocabularyData::_internal_mutable_word_ids() {
  return &_impl_.word_ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
VocabularyData::mutable_word_ids() {
  // @@protoc_insertion_point(field_mutable_list:jarvis.mapping.dbow.proto.VocabularyData.word_ids)
  return _internal_mutable_word_ids();
}

// -------------------------------------------------------------------

// VocabularyDatas

// repeated .jarvis.mapping.dbow.proto.VocabularyData vocabulary_datas = 1;
inline int VocabularyDatas::_internal_vocabulary_datas_size() const {
  return _impl_.vocabulary_datas_.size();
}
inline int VocabularyDatas::vocabulary_datas_size() const {
  return _internal_vocabulary_datas_size();
}
inline void VocabularyDatas::clear_vocabulary_datas() {
  _impl_.vocabulary_datas_.Clear();
}
inline ::jarvis::mapping::dbow::proto::VocabularyData* VocabularyDatas::mutable_vocabulary_datas(int index) {
  // @@protoc_insertion_point(field_mutable:jarvis.mapping.dbow.proto.VocabularyDatas.vocabulary_datas)
  return _impl_.vocabulary_datas_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::jarvis::mapping::dbow::proto::VocabularyData >*
VocabularyDatas::mutable_vocabulary_datas() {
  // @@protoc_insertion_point(field_mutable_list:jarvis.mapping.dbow.proto.VocabularyDatas.vocabulary_datas)
  return &_impl_.vocabulary_datas_;
}
inline const ::jarvis::mapping::dbow::proto::VocabularyData& VocabularyDatas::_internal_vocabulary_datas(int index) const {
  return _impl_.vocabulary_datas_.Get(index);
}
inline const ::jarvis::mapping::dbow::proto::VocabularyData& VocabularyDatas::vocabulary_datas(int index) const {
  // @@protoc_insertion_point(field_get:jarvis.mapping.dbow.proto.VocabularyDatas.vocabulary_datas)
  return _internal_vocabulary_datas(index);
}
inline ::jarvis::mapping::dbow::proto::VocabularyData* VocabularyDatas::_internal_add_vocabulary_datas() {
  return _impl_.vocabulary_datas_.Add();
}
inline ::jarvis::mapping::dbow::proto::VocabularyData* VocabularyDatas::add_vocabulary_datas() {
  ::jarvis::mapping::dbow::proto::VocabularyData* _add = _internal_add_vocabulary_datas();
  // @@protoc_insertion_point(field_add:jarvis.mapping.dbow.proto.VocabularyDatas.vocabulary_datas)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::jarvis::mapping::dbow::proto::VocabularyData >&
VocabularyDatas::vocabulary_datas() const {
  // @@protoc_insertion_point(field_list:jarvis.mapping.dbow.proto.VocabularyDatas.vocabulary_datas)
  return _impl_.vocabulary_datas_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace dbow
}  // namespace mapping
}  // namespace jarvis

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_jarvis_2fmapping_2fdbow_2fproto_2fvocabulary_5fdata_2eproto
